# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f82d01d81338c164b67cd47216777eafc8e586e205379371109d08e7f6fbb4f88984d5ea77d9b39f6b2809b792db16a29316273dd9caf1637c799070bbc7ca

test:
  secret_key_base: 95bc277a4b0325b53b43ca58ca380fb5f6f9f69e6239ad3c76486d6dd56550652100c389da2440d89e484105e49443a315c9c1eda04c8dea7f8eb7ae9eed85a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
